# Generated by Django 3.0.6 on 2020-06-07 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0002_auto_20200603_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 11, 23, 848862, tzinfo=utc)),
        ),
    ]
